# Generated by Django 5.2.11 on 2026-03-26 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_acquired', models.DateField(default=django.utils.timezone.now)),
                ('initial_count', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('sold', 'Sold')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_acquired'],
            },
        ),
        migrations.CreateModel(
            name='FlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase', 'Purchase'), ('death', 'Death'), ('cull', 'Cull'), ('transfer', 'Transfer'), ('sale', 'Sale')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='flock.flock')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EggProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(default=django.utils.timezone.now)),
                ('broken_crates', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('small_crates', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('medium_crates', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('big_crates', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_logs', to='flock.flock')),
            ],
            options={
                'ordering': ['-recorded_date'],
                'unique_together': {('flock', 'recorded_date')},
            },
        ),
    ]
