# Generated by Django 5.2.11 on 2026-02-12 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egg Type',
                'verbose_name_plural': 'Egg Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('broken_crates', models.IntegerField(default=0)),
                ('small_crates', models.IntegerField(default=0)),
                ('medium_crates', models.IntegerField(default=0)),
                ('big_crates', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intake Log',
                'verbose_name_plural': 'Intake Logs',
                'ordering': ['-recorded_date'],
                'indexes': [models.Index(fields=['recorded_date'], name='inventory_i_recorde_4cecc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('retail', 'Retail (Single Sales)'), ('wholesale_base', 'Base Wholesale')], max_length=20)),
                ('price_per_crate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('egg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.eggtype')),
            ],
            options={
                'verbose_name': 'Price Tier',
                'verbose_name_plural': 'Price Tiers',
                'ordering': ['-effective_date', 'tier'],
                'unique_together': {('tier', 'egg_type', 'effective_date')},
            },
        ),
    ]
