# Generated by Django 5.2.11 on 2026-02-12 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wholesale Customer',
                'verbose_name_plural': 'Wholesale Customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_w_name_c9958c_idx'), models.Index(fields=['is_active'], name='customers_w_is_acti_0dffe8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_crate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('egg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_overrides', to='inventory.eggtype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='customers.wholesalecustomer')),
            ],
            options={
                'verbose_name': 'Customer Price Override',
                'verbose_name_plural': 'Customer Price Overrides',
                'ordering': ['-effective_date'],
                'unique_together': {('customer', 'egg_type', 'effective_date')},
            },
        ),
    ]
