# Generated by Django 5.2.11 on 2026-02-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPriceOverride',
        ),
    ]
