# Generated by Django 5.2.11 on 2026-02-12 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('retail', 'Retail (Single Sales)'), ('wholesale', 'Wholesale')], max_length=20)),
                ('sale_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('broken_quantity', models.IntegerField(default=0)),
                ('small_quantity', models.IntegerField(default=0)),
                ('medium_quantity', models.IntegerField(default=0)),
                ('big_quantity', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.wholesalecustomer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_datetime'],
                'indexes': [models.Index(fields=['sale_datetime'], name='sales_sale_sale_da_958b5b_idx'), models.Index(fields=['sale_type'], name='sales_sale_sale_ty_7f3885_idx'), models.Index(fields=['customer'], name='sales_sale_custome_f0dcab_idx')],
            },
        ),
    ]
