# Generated by Django 5.2.11 on 2026-02-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='big_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='broken_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='medium_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='small_quantity',
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price_per_crate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('egg_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.eggtype')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'indexes': [models.Index(fields=['sale', 'egg_type'], name='sales_salei_sale_id_92a698_idx')],
            },
        ),
    ]
